title: Resume
url: "https://github.com/high-in-entropy/resume2"
baseurl: "/resume2"

markdown: kramdown
ins_logo: "./svnitlogo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/high-in-entropy"
footer_text: "Viraj Mohile"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/Resume/"
 - name: "Projects"
   link: "projects"
 - name: "Blog"
   link: "bloglist"
 - name: "Contact"
   link: "contact"
